Update on-merge.yml

diff --git a/.github/workflows/on-merge.yml b/.github/workflows/on-merge.yml
--- a/.github/workflows/on-merge.yml
+++ b/.github/workflows/on-merge.yml
@@ -1,10 +1,9 @@
 name: On merge test
-
 on:
   workflow_dispatch:
-  push:
-#   pull_request:
-    branches: [ main ]
+  #push:
+  pull_request:
+      branches: [ main ]
 ## breaking change test
 jobs:
   on-push-ci:
@@ -16,10 +15,8 @@ jobs:
       contents: write
     
     steps:
-        
-        
       - name: Checkout
         run: echo "say hello"
 
-      - name: fail
-        run: exit 1
+      #- name: fail
+       # run: exit 1
