Update on-merge.yml

diff --git a/.github/workflows/on-merge.yml b/.github/workflows/on-merge.yml
--- a/.github/workflows/on-merge.yml
+++ b/.github/workflows/on-merge.yml
@@ -16,16 +16,16 @@ jobs:
     
     steps:
     
-      - name: Checkout
-        uses: actions/checkout@v3
-    
 #       - name: Checkout
-#         run: echo "say hello"
+#         uses: actions/checkout@v3
+    
+      - name: Checkout
+        run: echo "say hello"
 
-      - name: test failing
-        run: |
-          if [[ $(cat CI-helper.py | grep test22) == '#test22' ]]; 
-          then 
-            echo 'hello';
-            exit 1;
-          fi
+#       - name: test failing
+#         run: |
+#           if [[ $(cat CI-helper.py | grep test22) == '#test22' ]]; 
+#           then 
+#             echo 'hello';
+#             exit 1;
+#           fi
