Update on-pull-request.yml

diff --git a/.github/workflows/on-pull-request.yml b/.github/workflows/on-pull-request.yml
--- a/.github/workflows/on-pull-request.yml
+++ b/.github/workflows/on-pull-request.yml
@@ -21,6 +21,7 @@ jobs:
       AWS_ROLE: arn:aws:iam::331226338131:role/ci-GithubActionsRole
       #JOB_NAME: mmg-e2etest-job
       JOB_NAME: test-job
+      APP_NAME: myapp
     
     steps:
       - name: Checkout
@@ -51,14 +52,14 @@ jobs:
       - name: Generate image tag
         run: |
           timestamp=$(date +%Y%m%d%H%M%S)
-          echo "IMAGE_TAG=rc-$timestamp" >> $GITHUB_ENV
+          echo "RC_IMAGE_TAG=rc-$timestamp" >> $GITHUB_ENV
 
-#       - name: Build and push
-#         uses: docker/build-push-action@v2
-#         with:
-#           push: true
-#           #tags: ${{ env.DOCKER_USER }}/${{ env.DOCKER_HUB_REPO }}:latest, ${{ env.DOCKER_USER }}/${{ env.DOCKER_HUB_REPO }}:${{ steps.version.outputs.version }}
-#           tags: ${{ env.DOCKER_USER }}/${{ env.DOCKER_HUB_REPO }}:ci-helper
+      - name: Build and push
+        uses: docker/build-push-action@v2
+        with:
+          push: true
+          #tags: ${{ env.DOCKER_USER }}/${{ env.DOCKER_HUB_REPO }}:latest, ${{ env.DOCKER_USER }}/${{ env.DOCKER_HUB_REPO }}:${{ steps.version.outputs.version }}
+          tags: ${{ env.DOCKER_USER }}/${{ env.DOCKER_HUB_REPO }}:${{ env.RC_IMAGE_TAG }}
       
 #       - name: Create Release
 #         if: ${{ !startsWith(github.ref, 'refs/tags/') }}
@@ -92,7 +93,7 @@ jobs:
         with:
           version: v3.8.0
 
-      - name: Check if another CI is not in progress
+      - name: Check if another e2e-test is not in progress
         timeout-minutes: 10
         run: | 
           MARKER=$(kubectl get deploy ci-helper -o=jsonpath='{.spec.replicas}')
@@ -107,51 +108,45 @@ jobs:
 
 ### Alternative method which is better but requires adding additional labels to deployment
 ### https://stackoverflow.com/questions/53450759/helm-upgrade-install-isnt-picking-up-new-changes
-#       - name: Get current image tag in release
-#         run: |
-#           echo "CURRENT_TAG=$(helm get values myapp | sed -n -e 's/^.*tag: //p')" >> $GITHUB_ENV
-        
-#       - name: Deploy
-#         run: helm upgrade --install --set image.repository="${{ env.DOCKER_USER }}/${{ env.DOCKER_HUB_REPO }}" --set image.tag=ci-helper ci-helper testchart
-      
-#       - name: Run test job
-#         id: test_job
-#         run: kubectl replace --force -f mec_kubernetes/${{ env.JOB_NAME }}.yml
-        
-#       - name: Get test job pod name
-#         run: |
-#           E2E_POD_TMP=$(kubectl get pods --selector=job-name=${{ env.JOB_NAME }} --sort-by=.status.startTime | sed -n '$p' | awk '{print $1}')
-#           echo "E2E_POD=$E2E_POD_TMP" >> $GITHUB_ENV
-          
-#       - name: Check job status
-#         timeout-minutes: 5
-#         run: |
-#           JOB_STATUS=$(kubectl get pods ${{ env.E2E_POD }} --no-headers -o custom-columns=':status.phase')
-#           while [ $JOB_STATUS != "Succeeded" ]
-#           do
-#             JOB_STATUS=$(kubectl get pods ${{ env.E2E_POD }} --no-headers -o custom-columns=':status.phase')
-#           done
-      
-#       - name: Get test results
-#         run: |
-#           TEST_FAILED_TMP=$(kubectl logs ${{ env.E2E_POD }} | grep 'All Test Done' | sed -e 's/.*total fail \(.\).*\*\*\*/\1/')
-#           echo "TEST_FAILED=$TEST_FAILED_TMP" >> $GITHUB_ENV
-      
-#       - name: Rollback to previous version
-#         #helm upgrade --install --set image.repository="${{ env.DOCKER_USER }}/${{ env.DOCKER_HUB_REPO }}" --set image.tag=${{ env.CURRENT_TAG }} myapp testchart
-          
-#       - name: Show e2e-test result
-#         run: |
-#           if [ ${{ env.TEST_FAILED }} -nq 0 ]; then
-#             echo "Count of failed tests: " ${{ env.TEST_FAILED }}
-#             echo "Complete logs output:" && kubectl logs ${{ env.E2E_POD }}
-#             exit 1
-#           fi
-   
-      - name: test ci-helper
+      - name: Get current image tag in release
         run: |
-          sleep 30
-          kubectl get po
+          echo "CURRENT_TAG=$(helm get values ${{ env.APP_NAME }} | sed -n -e 's/^.*tag: //p')" >> $GITHUB_ENV
+        
+      - name: Deploy
+        run: helm upgrade --install --set image.repository="${{ env.DOCKER_USER }}/${{ env.DOCKER_HUB_REPO }}" --set image.tag=${{ env. RC_IMAGE_TAG }} ${{ env.APP_NAME }} testchart
+      
+      - name: Run test job
+        run: kubectl replace --force -f mec_kubernetes/${{ env.JOB_NAME }}.yml
+        
+      - name: Get test job pod name
+        run: |
+          E2E_POD_TMP=$(kubectl get pods --selector=job-name=${{ env.JOB_NAME }} --sort-by=.status.startTime | sed -n '$p' | awk '{print $1}')
+          echo "E2E_POD=$E2E_POD_TMP" >> $GITHUB_ENV
+          
+      - name: Check job status
+        timeout-minutes: 5
+        run: |
+          JOB_STATUS=$(kubectl get pods ${{ env.E2E_POD }} --no-headers -o custom-columns=':status.phase')
+          while [ $JOB_STATUS != "Succeeded" ]
+          do
+            JOB_STATUS=$(kubectl get pods ${{ env.E2E_POD }} --no-headers -o custom-columns=':status.phase')
+          done
+      
+      - name: Get test results
+        run: |
+          TEST_FAILED_TMP=$(kubectl logs ${{ env.E2E_POD }} | grep 'All Test Done' | sed -e 's/.*total fail \(.\).*\*\*\*/\1/')
+          echo "TEST_FAILED=$TEST_FAILED_TMP" >> $GITHUB_ENV
+      
+      #- name: Rollback to previous version
+        #helm upgrade --install --set image.repository="${{ env.DOCKER_USER }}/${{ env.DOCKER_HUB_REPO }}" --set image.tag=${{ env.CURRENT_TAG }} ${{ env.RC_IMAGE_TAG }} testchart
+          
+      - name: Show e2e-test result
+        run: |
+          if [ ${{ env.TEST_FAILED }} -nq 0 ]; then
+            echo "Count of failed tests: " ${{ env.TEST_FAILED }}
+            echo "Complete logs output:" && kubectl logs ${{ env.E2E_POD }}
+            exit 1
+          fi
           
       - name: Release marker in ci-helper
         run: kubectl scale deployment ci-helper --replicas=0
